{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "ethereum-kit-erc20",
    "version": "99d3195",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-erc20-99d3195.aar",
          "url": "ethereum-kit-erc20-99d3195.aar",
          "size": 96821,
          "sha512": "4a6364162f6001c27d94da86b0c0072a6f96bfa9a7692389f76b8d5baaa386e74587eaf7fc2128786f8bd225bffb4906a6307fef2a26529c0902d906940221d8",
          "sha256": "369da62b44e13dca297e462229809b7652e0d44fc76ee17b1d5a3b7215f9c764",
          "sha1": "a3a55ba43921408fc0b9295bfcf89be76b534723",
          "md5": "abe4a153d3ea2f90512767c1108c5ab2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "ethereum-kit-android",
          "version": {
            "requires": "99d3195"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-erc20-99d3195.aar",
          "url": "ethereum-kit-erc20-99d3195.aar",
          "size": 96821,
          "sha512": "4a6364162f6001c27d94da86b0c0072a6f96bfa9a7692389f76b8d5baaa386e74587eaf7fc2128786f8bd225bffb4906a6307fef2a26529c0902d906940221d8",
          "sha256": "369da62b44e13dca297e462229809b7652e0d44fc76ee17b1d5a3b7215f9c764",
          "sha1": "a3a55ba43921408fc0b9295bfcf89be76b534723",
          "md5": "abe4a153d3ea2f90512767c1108c5ab2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-erc20-99d3195-sources.jar",
          "url": "ethereum-kit-erc20-99d3195-sources.jar",
          "size": 69828,
          "sha512": "cfbd53a263b40bbe80ae125145f4f9dcfa830b626996413fbfa2ede6ace137241c3482ed109a942ac9909340bda542b34467ba39562b3ac2e4f1f5ddf56a342b",
          "sha256": "aad19cb99ef0a447e1bd54297dc0b670b23f66d21dcddadcd289e92510616242",
          "sha1": "1deb6bd3545deec00b2d4712ba4314a72ea3831d",
          "md5": "086d097c57cf355f9a876d3e5668ad5e"
        }
      ]
    }
  ]
}
