{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "ethereum-kit-erc20",
    "version": "633b922",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-erc20-633b922.aar",
          "url": "ethereum-kit-erc20-633b922.aar",
          "size": 96728,
          "sha512": "97252eeb07fc6a7f1edbc55fc4dcdc8271128a98d436f4f1bf9785f3dc47fd76862b9250352ceb425f4fff5b90456b32042422b7a667a79a3cb5936db5718753",
          "sha256": "9c8e0223e994a681919d87b0c1c4693aecc4225450993f1c3744b8654230cb96",
          "sha1": "9d20524193eb5b716ef32735d754ef467c07531a",
          "md5": "90608c3cb283e1191a3b9af39e777aeb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "ethereum-kit-android",
          "version": {
            "requires": "633b922"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-erc20-633b922.aar",
          "url": "ethereum-kit-erc20-633b922.aar",
          "size": 96728,
          "sha512": "97252eeb07fc6a7f1edbc55fc4dcdc8271128a98d436f4f1bf9785f3dc47fd76862b9250352ceb425f4fff5b90456b32042422b7a667a79a3cb5936db5718753",
          "sha256": "9c8e0223e994a681919d87b0c1c4693aecc4225450993f1c3744b8654230cb96",
          "sha1": "9d20524193eb5b716ef32735d754ef467c07531a",
          "md5": "90608c3cb283e1191a3b9af39e777aeb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-erc20-633b922-sources.jar",
          "url": "ethereum-kit-erc20-633b922-sources.jar",
          "size": 69813,
          "sha512": "712e3752f832b561f1b26db707c7a9ce0646c5fca483ed52800d4b0333a255717e290c40093d26bb7ea5a7be81bc9284f507393c9b5cb2b76bd9a7ee445ad95e",
          "sha256": "ec4f9aee7b527879ca0a031b3a5ce2af0b34ce31e07034f6297637a66a7d736d",
          "sha1": "7bf29f0109b140bb5e708e1c672092beea6c462e",
          "md5": "ecfa14a57df1ecf7781f5bc954ef5830"
        }
      ]
    }
  ]
}
