{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "ethereum-kit-android",
    "version": "4e45186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.web3j",
          "module": "abi",
          "version": {
            "requires": "4.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-android-4e45186.aar",
          "url": "ethereum-kit-android-4e45186.aar",
          "size": 746597,
          "sha512": "54135519c98609dfa22696ec2d150ac1cd7469ef172c45474929ca220b716ff57ce9a312539d5e4c382048ecbeeb1c37cd5a0541872af761eb1c100a6042e9bd",
          "sha256": "e2419bdb3b3be7a5bc9559772cb4dc42fb14c5cfefe28a5a0ffaa9840c9a9faa",
          "sha1": "3bcf6e852ee8df68968fb736a028e4fed4286284",
          "md5": "d0734590c00a169278638deaf75c8ea9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "hd-wallet-kit-android",
          "version": {
            "requires": "8f873a1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "lifecycle-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.web3j",
          "module": "crypto",
          "version": {
            "requires": "4.9.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.web3j",
          "module": "abi",
          "version": {
            "requires": "4.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-android-4e45186.aar",
          "url": "ethereum-kit-android-4e45186.aar",
          "size": 746597,
          "sha512": "54135519c98609dfa22696ec2d150ac1cd7469ef172c45474929ca220b716ff57ce9a312539d5e4c382048ecbeeb1c37cd5a0541872af761eb1c100a6042e9bd",
          "sha256": "e2419bdb3b3be7a5bc9559772cb4dc42fb14c5cfefe28a5a0ffaa9840c9a9faa",
          "sha1": "3bcf6e852ee8df68968fb736a028e4fed4286284",
          "md5": "d0734590c00a169278638deaf75c8ea9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-android-4e45186-sources.jar",
          "url": "ethereum-kit-android-4e45186-sources.jar",
          "size": 550803,
          "sha512": "d3976dc3af592801b7e2a4bd1688dabacda054e00441121ad654e1a770ad5894fdd50bba0d39e9b98ba149d99add51a2c68501610104f184734763f2c1280f4b",
          "sha256": "810523c7be91ea0116bb4db28b435acc4dad8d8b02844f168ed4dbd40dc404a6",
          "sha1": "83b68de7b1968653316b1e52f399b8ed3aba6525",
          "md5": "45be7cda7fe0e4e06bd42799b7c79148"
        }
      ]
    }
  ]
}
