{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "ethereum-kit-uniswap",
    "version": "4e45186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-uniswap-4e45186.aar",
          "url": "ethereum-kit-uniswap-4e45186.aar",
          "size": 203317,
          "sha512": "fdc09b23c8cc6c215b77c996ae0d29416246ceb59dc64f969e0f743b1b19dfd0d6e721d0a006772222a49d71475200f6a222cd27ca8947a3a410f6f61bc319f7",
          "sha256": "33aefb55ec7ab3400a296b52ad4bc194727a18a89c9fe6447d7ffc1916787cc2",
          "sha1": "b8f71f5f7895a4feedf36d01d2ba74e228136e07",
          "md5": "d1e7cb8ae459f9c55f5637ee1f9f5cff"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "ethereum-kit-android",
          "version": {
            "requires": "4e45186"
          }
        },
        {
          "group": "com.github.piratecash",
          "module": "ethereum-kit-erc20",
          "version": {
            "requires": "4e45186"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "ethereum-kit-uniswap-4e45186.aar",
          "url": "ethereum-kit-uniswap-4e45186.aar",
          "size": 203317,
          "sha512": "fdc09b23c8cc6c215b77c996ae0d29416246ceb59dc64f969e0f743b1b19dfd0d6e721d0a006772222a49d71475200f6a222cd27ca8947a3a410f6f61bc319f7",
          "sha256": "33aefb55ec7ab3400a296b52ad4bc194727a18a89c9fe6447d7ffc1916787cc2",
          "sha1": "b8f71f5f7895a4feedf36d01d2ba74e228136e07",
          "md5": "d1e7cb8ae459f9c55f5637ee1f9f5cff"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ethereum-kit-uniswap-4e45186-sources.jar",
          "url": "ethereum-kit-uniswap-4e45186-sources.jar",
          "size": 134392,
          "sha512": "6f613883c27a8578a669e6e59070ca0c1a35f20123f7ba1fd9e28d57ccc3d91a2622ad39fe2bf30e7d1715bc22342077139bdf9d4c1e59767ad27e21c8b92b0e",
          "sha256": "ed42e2528e1057bf47f6b597661edc18bf932dc44ed964b7e96ef6ba9a1f2cb4",
          "sha1": "7ac869f42878df85cd20fc9480563bf011d87283",
          "md5": "19393d9465836684096e7491e14346c2"
        }
      ]
    }
  ]
}
